{% set name = "crossenv" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crossenv-{{ version }}.tar.gz
  sha256: c355265e36335dd49a102d5466d942f8c6c10e728ad2eaa7163c90f61e0ca985

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - crossenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benfogle/crossenv
  summary: A cross-compiling tool for Python extension modules
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - isuruf
